### ISSUE TITLE
create_icc: CGColorSyncTransformCacheGetRetained failed

### ISSUE THREAD

**Issue by wensbo** [SDWebImage/SDWebImageAVIFCoder#37] opened 2022-07-28 03:32 UTC
<img width="1760" alt="截屏2022-07-28 11 31 27" src="https://user-images.githubusercontent.com/17174309/181414558-6320cad8-6b21-4e3e-8cd2-1bd346681922.png">

Incidental problem

url：https://image.video.qpic.cn/app_community_efcccd-0_1525530205_1655593948638998?imageView2/2/w/375/format/avif

SDWebImage (5.13.2)

**Comment by dreampiggy** [comment] 2022-07-28 06:13
Is this caused by libavif version ?

**Comment by wensbo** [comment] 2022-07-28 07:56
simulator is a appear, the real machine does not reappear. It doesn't matter what version

<img width="1071" alt="截屏2022-07-28 15 54 23" src="https://user-images.githubusercontent.com/17174309/181452386-b40c191c-5f03-4baa-bdc2-082cff1e71a3.png">

When I use CFDataCreate, there's no problem

**Comment by dreampiggy** [comment] 2022-07-28 09:54
Seems behavior changes. Because at that time (one year ago), the ICCProfile data does not need a extra copy (which take time)

Provide the detail reproduce environment:

+ iOS version
+ iPhone firmware device model
+ SDWebImage, SDWebImageAVIFCoder, etc, Podfile.lock

**Comment by wensbo** [comment] 2022-07-28 11:31
![截屏2022-07-28 19 28 14](https://user-images.githubusercontent.com/17174309/181494637-857127d7-1c6d-4fba-92fc-ac2757a903d5.png)
<img width="325" alt="截屏2022-07-28 19 29 22" src="https://user-images.githubusercontent.com/17174309/181494762-88c92a5a-9d2d-4771-b5a6-57d6233918d8.png">

Always network download, try again. Will reappear

<img width="1302" alt="截屏2022-07-28 19 27 18" src="https://user-images.githubusercontent.com/17174309/181494784-bab23aaa-d1be-4514-bde2-26a0a3dcaa6c.png">

**Comment by dreampiggy** [comment] 2022-07-28 12:18
> simulator is a appear, the real machine does not reappear. It doesn't matter what version

What is that means ? Only contains bug on iPhone simulator ?

**Comment by wensbo** [comment] 2022-07-28 14:35
Currently found only on the simulator

**Comment by dreampiggy** [comment] 2022-08-11 09:52
Should be fixed in #40.

**Closed** 2022-08-11 10:02 UTC

**Comment by dreampiggy** [comment] 2022-08-12 06:53
Released in [v0.9.3](https://github.com/SDWebImage/SDWebImageAVIFCoder/releases/tag/0.9.3)
